# Generated by Django 5.1.2 on 2024-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_rename_name_students_studentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetAddress', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('minicipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField(max_length=4)),
            ],
        ),
    ]
