DELETE http://127.0.0.1:8000/api/auth/users/
Content-Type: application/json

{
    "id": 2
}

###

GET http://127.0.0.1:8000/api/auth/users/

###

PATCH http://127.0.0.1:8000/api/auth/users/
Content-Type: application/json

{
    "id": 1,
    "old_password": "Glenda",
    "password": "glenda",
    "password_confirmation": "glenda"
}
###

PATCH http://127.0.0.1:8000/api/students/6/
Content-Type: application/json

{
    "schoolYear": 2024,
            "firstName": "zanjoe",
            "middleName": "middle",
            "lastName": "gonzales",
            "grade": 12,
            "gender": "male",
            "age": 20,
            "address": {
                "id": 4,
                "province": "Taytay",
                "municipality": "Angat",
                "zipCode": 1920,
                "city": "Manila",
                "barangay": "Barangay 7",
                "streetAddress": "blk 49"
            },
            "section": "DTS IT-1E2",
            "status": "Dying...."
}

###

DELETE http://127.0.0.1:8000/api/students
Content-Type: application/json

{
    "id": 1
}